apiVersion: v1
kind: Pod
metadata:
  name: pvc-writer-fullerton
  namespace: csuf-titans
spec:
  restartPolicy: Never
  containers:
  - name: sh
    image: busybox
    command: ["sleep","3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: cpsc488-pvc-fullerton

apiVersion: batch/v1
kind: Job
metadata:
  name: cpsc488-train
  namespace: csuf-titans
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: trainer
        image: bebopkenny/cpsc488-a1:gpu
        workingDir: /app
        args: ["/data/GasProperties.csv"]  # dataset on PVC
        env:
        - name: OMP_NUM_THREADS
          value: "4"
        - name: MKL_NUM_THREADS
          value: "4"
        resources:
          requests:
            cpu: "4"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "4Gi"
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cpsc488-pvc-fullerton