apiVersion: batch/v1
kind: Job
metadata:
  name: cpsc488-a4-finetune
  namespace: csuf-titans
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: cpsc488-a4
    spec:
      restartPolicy: Never
      containers:
      - name: trainer
        image: bebopkenny/cpsc488-a4:gpu
        command: ["python", "main.py"]
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: "1"
          limits:
            memory: "32Gi"
            cpu: "8"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: cpsc488-a4-storage
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 8Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A100-SXM4-40GB
                - NVIDIA-A100-PCIE-40GB
                - Tesla-V100-SXM2-32GB
