apiVersion: v1
kind: Pod
metadata:
  name: pvc-reader
  namespace: csuf-titans
spec:
  containers:
  - name: reader
    image: alpine:latest
    command: ["sleep", "3600"]
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: cpsc488-a4-storage
  restartPolicy: Never
