apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpsc488-a4-storage
  namespace: csuf-titans
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-ceph-block
