# k8s-pvc.yaml
# Persistent Volume Claim for Assignment 4
# Only needed if you don't already have cpsc488-pvc-fullerton
#
# Usage:
#   kubectl apply -f k8s-pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cpsc488-pvc-fullerton
  namespace: csuf-titans
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: rook-ceph-block-fullerton
  resources:
    requests:
      storage: 50Gi